apiVersion: v1
kind: Pod
metadata:
  name: hposvolume-pod
    #  namespace: testing
spec:
  containers:
    - name: con1
      image: nginx
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: demo
