apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo
spec:
  storageClassName: hostpath-on-steriod
  resources:
    requests:
      storage: 1G
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
