apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csi-driver-hostpath-on-steriod.serviceAccountName" . }}
  labels:
    {{- include "csi-driver-hostpath-on-steriod.labels" . | nindent 4 }}