apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpos-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hpos-cr
subjects:
- kind: ServiceAccount
  name: hpos-sa
  namespace: testing
