apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hostpath-on-steriod-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hostpath-on-steriod-cr
subjects:
- kind: ServiceAccount
  name: hostpath-on-steriod-sa
  namespace: testing
