apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-driver-hostpath-on-steriods-deploy
  namespace: testing
spec:
  selector:
    matchLabels:
      app: csi-driver-hostpath-on-steriod
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-driver-hostpath-on-steriod
      name: csi-driver
    spec:
      serviceAccountName: hostpath-on-steriod-sa
      containers:
        - name: csi-driver
          image: shilucloud/csi-driver-hostpath-on-steriod:local
          args:
            - --endpoint=unix:///var/run/csi.sock
            - --name=csi.driver.hostpath.on.steriod
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run

        - name: external-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v6.2.0
          args:
            - "--csi-address=unix:///var/run/csi.sock"
            - "--v=5"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run
      volumes:
        - name: socket-dir
          emptyDir: {}

