apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-node-driver
  namespace: testing
spec:
  selector:
    matchLabels:
      app: csi-driver-hostpath-on-steriod
      csi-driver-component: node
  template:
    metadata:
      name: csi-node-driver-pod
      labels:
        app: csi-driver-hostpath-on-steriod
        csi-driver-component: node
    spec:
      containers:
        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.16.0
          args:
            - "--csi-address=/var/run/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi.driver.hostpath.on.steriod/csi.sock"
            - --v=5
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/
            - name: registration-dir
              mountPath: /registration

        - name: csi-driver
          image: shilucloud/csi-driver-hostpath-on-steriod:local
          args:
            - --endpoint=unix:///var/run/csi.sock
            - --mode=node
            - --name=csi.driver.hostpath.on.steriod
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: dev
              mountPath: /dev

            - name: socket-dir
              mountPath: /var/run/
            
            - name: hpos-data
              mountPath: /var/lib/hpos

            - name: staging-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
          
          securityContext:
            privileged: true
              
      volumes:
        - name: dev
          hostPath:
            path: /dev
            
        - name: hpos-data
          hostPath:
            path: /var/lib/hpos
            type: DirectoryOrCreate

        - name: hpos-snapshot-data
          hostPath:
            path: /var/lib/hpos/snapshots
            type: DirectoryOrCreate
        
        - name: staging-dir 
          hostPath:
            path: /var/lib/kubelet 
            type: DirectoryOrCreate

        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory

        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.driver.hostpath.on.steriod//
            type: DirectoryOrCreate