apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath-on-steriod

volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: xfs 
provisioner: csi.driver.hostpath.on.steriod
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
          - kind-control-plane
