image:
  repository: shilucloud/csi-driver-hostpath-on-steriod
  tag: "local"
  pullPolicy: IfNotPresent

controller:
  replicas: 1
  resources: {}

node:
  resources: {}

sidecars:
  provisioner:
    image: registry.k8s.io/sig-storage/csi-provisioner
    tag: "v6.2.0"
    resources: {}

  attacher:
    image: registry.k8s.io/sig-storage/csi-attacher
    tag: "v4.11.0"
    resources: {}

  nodeDriverRegistrar:
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar
    tag: "v2.16.0"
    resources: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

crd:
  group: shilu.cloud

fullnameOverride: "hpos"


driverName: csi.driver.hostpath.on.steriod